export const SIGN_UP_INTRODUCTION = 0;
export const SIGN_UP_SELF_CERTIFICATION = 1;
export const SIGN_UP_ACCOUNT_CREATION_FROM = 2;
export const SIGN_UP_INFORMATION_FORM = 3;
export const SIGN_UP_PROFILE_PICTURE = 4;
